project_id = "lgscevufwnetegglgpnw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lgscevufwnetegglgpnw.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
security_update_email_require_reauthentication = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_email_change_enabled = true
enable_reauthentication = true
enable_password_protection = true

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[functions.lemon-squeezy-webhook]
verify_jwt = false

[functions.lemon-squeezy-checkout]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.get-admin-users]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.todoist-feedback]
verify_jwt = true

[functions.pricing-config]
verify_jwt = false

[functions.publish-scheduled-courses]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.publish-scheduled-blog]
verify_jwt = false

[functions.send-discount-email]
verify_jwt = false

[edge_runtime]
policy = "per_worker"
inspector_port = 8083